// Code generated by 'yaegi extract github.com/jroimartin/gocui'. DO NOT EDIT.

package symbols

import (
	"github.com/jroimartin/gocui"
	"reflect"
)

func init() {
	Symbols["github.com/jroimartin/gocui/gocui"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AttrBold":          reflect.ValueOf(gocui.AttrBold),
		"AttrReverse":       reflect.ValueOf(gocui.AttrReverse),
		"AttrUnderline":     reflect.ValueOf(gocui.AttrUnderline),
		"ColorBlack":        reflect.ValueOf(gocui.ColorBlack),
		"ColorBlue":         reflect.ValueOf(gocui.ColorBlue),
		"ColorCyan":         reflect.ValueOf(gocui.ColorCyan),
		"ColorDefault":      reflect.ValueOf(gocui.ColorDefault),
		"ColorGreen":        reflect.ValueOf(gocui.ColorGreen),
		"ColorMagenta":      reflect.ValueOf(gocui.ColorMagenta),
		"ColorRed":          reflect.ValueOf(gocui.ColorRed),
		"ColorWhite":        reflect.ValueOf(gocui.ColorWhite),
		"ColorYellow":       reflect.ValueOf(gocui.ColorYellow),
		"DefaultEditor":     reflect.ValueOf(&gocui.DefaultEditor).Elem(),
		"ErrQuit":           reflect.ValueOf(&gocui.ErrQuit).Elem(),
		"ErrUnknownView":    reflect.ValueOf(&gocui.ErrUnknownView).Elem(),
		"KeyArrowDown":      reflect.ValueOf(gocui.KeyArrowDown),
		"KeyArrowLeft":      reflect.ValueOf(gocui.KeyArrowLeft),
		"KeyArrowRight":     reflect.ValueOf(gocui.KeyArrowRight),
		"KeyArrowUp":        reflect.ValueOf(gocui.KeyArrowUp),
		"KeyBackspace":      reflect.ValueOf(gocui.KeyBackspace),
		"KeyBackspace2":     reflect.ValueOf(gocui.KeyBackspace2),
		"KeyCtrl2":          reflect.ValueOf(gocui.KeyCtrl2),
		"KeyCtrl3":          reflect.ValueOf(gocui.KeyCtrl3),
		"KeyCtrl4":          reflect.ValueOf(gocui.KeyCtrl4),
		"KeyCtrl5":          reflect.ValueOf(gocui.KeyCtrl5),
		"KeyCtrl6":          reflect.ValueOf(gocui.KeyCtrl6),
		"KeyCtrl7":          reflect.ValueOf(gocui.KeyCtrl7),
		"KeyCtrl8":          reflect.ValueOf(gocui.KeyCtrl8),
		"KeyCtrlA":          reflect.ValueOf(gocui.KeyCtrlA),
		"KeyCtrlB":          reflect.ValueOf(gocui.KeyCtrlB),
		"KeyCtrlBackslash":  reflect.ValueOf(gocui.KeyCtrlBackslash),
		"KeyCtrlC":          reflect.ValueOf(gocui.KeyCtrlC),
		"KeyCtrlD":          reflect.ValueOf(gocui.KeyCtrlD),
		"KeyCtrlE":          reflect.ValueOf(gocui.KeyCtrlE),
		"KeyCtrlF":          reflect.ValueOf(gocui.KeyCtrlF),
		"KeyCtrlG":          reflect.ValueOf(gocui.KeyCtrlG),
		"KeyCtrlH":          reflect.ValueOf(gocui.KeyCtrlH),
		"KeyCtrlI":          reflect.ValueOf(gocui.KeyCtrlI),
		"KeyCtrlJ":          reflect.ValueOf(gocui.KeyCtrlJ),
		"KeyCtrlK":          reflect.ValueOf(gocui.KeyCtrlK),
		"KeyCtrlL":          reflect.ValueOf(gocui.KeyCtrlL),
		"KeyCtrlLsqBracket": reflect.ValueOf(gocui.KeyCtrlLsqBracket),
		"KeyCtrlM":          reflect.ValueOf(gocui.KeyCtrlM),
		"KeyCtrlN":          reflect.ValueOf(gocui.KeyCtrlN),
		"KeyCtrlO":          reflect.ValueOf(gocui.KeyCtrlO),
		"KeyCtrlP":          reflect.ValueOf(gocui.KeyCtrlP),
		"KeyCtrlQ":          reflect.ValueOf(gocui.KeyCtrlQ),
		"KeyCtrlR":          reflect.ValueOf(gocui.KeyCtrlR),
		"KeyCtrlRsqBracket": reflect.ValueOf(gocui.KeyCtrlRsqBracket),
		"KeyCtrlS":          reflect.ValueOf(gocui.KeyCtrlS),
		"KeyCtrlSlash":      reflect.ValueOf(gocui.KeyCtrlSlash),
		"KeyCtrlSpace":      reflect.ValueOf(gocui.KeyCtrlSpace),
		"KeyCtrlT":          reflect.ValueOf(gocui.KeyCtrlT),
		"KeyCtrlTilde":      reflect.ValueOf(gocui.KeyCtrlTilde),
		"KeyCtrlU":          reflect.ValueOf(gocui.KeyCtrlU),
		"KeyCtrlUnderscore": reflect.ValueOf(gocui.KeyCtrlUnderscore),
		"KeyCtrlV":          reflect.ValueOf(gocui.KeyCtrlV),
		"KeyCtrlW":          reflect.ValueOf(gocui.KeyCtrlW),
		"KeyCtrlX":          reflect.ValueOf(gocui.KeyCtrlX),
		"KeyCtrlY":          reflect.ValueOf(gocui.KeyCtrlY),
		"KeyCtrlZ":          reflect.ValueOf(gocui.KeyCtrlZ),
		"KeyDelete":         reflect.ValueOf(gocui.KeyDelete),
		"KeyEnd":            reflect.ValueOf(gocui.KeyEnd),
		"KeyEnter":          reflect.ValueOf(gocui.KeyEnter),
		"KeyEsc":            reflect.ValueOf(gocui.KeyEsc),
		"KeyF1":             reflect.ValueOf(gocui.KeyF1),
		"KeyF10":            reflect.ValueOf(gocui.KeyF10),
		"KeyF11":            reflect.ValueOf(gocui.KeyF11),
		"KeyF12":            reflect.ValueOf(gocui.KeyF12),
		"KeyF2":             reflect.ValueOf(gocui.KeyF2),
		"KeyF3":             reflect.ValueOf(gocui.KeyF3),
		"KeyF4":             reflect.ValueOf(gocui.KeyF4),
		"KeyF5":             reflect.ValueOf(gocui.KeyF5),
		"KeyF6":             reflect.ValueOf(gocui.KeyF6),
		"KeyF7":             reflect.ValueOf(gocui.KeyF7),
		"KeyF8":             reflect.ValueOf(gocui.KeyF8),
		"KeyF9":             reflect.ValueOf(gocui.KeyF9),
		"KeyHome":           reflect.ValueOf(gocui.KeyHome),
		"KeyInsert":         reflect.ValueOf(gocui.KeyInsert),
		"KeyPgdn":           reflect.ValueOf(gocui.KeyPgdn),
		"KeyPgup":           reflect.ValueOf(gocui.KeyPgup),
		"KeySpace":          reflect.ValueOf(gocui.KeySpace),
		"KeyTab":            reflect.ValueOf(gocui.KeyTab),
		"ModAlt":            reflect.ValueOf(gocui.ModAlt),
		"ModNone":           reflect.ValueOf(gocui.ModNone),
		"MouseLeft":         reflect.ValueOf(gocui.MouseLeft),
		"MouseMiddle":       reflect.ValueOf(gocui.MouseMiddle),
		"MouseRelease":      reflect.ValueOf(gocui.MouseRelease),
		"MouseRight":        reflect.ValueOf(gocui.MouseRight),
		"MouseWheelDown":    reflect.ValueOf(gocui.MouseWheelDown),
		"MouseWheelUp":      reflect.ValueOf(gocui.MouseWheelUp),
		"NewGui":            reflect.ValueOf(gocui.NewGui),
		"Output256":         reflect.ValueOf(gocui.Output256),
		"OutputNormal":      reflect.ValueOf(gocui.OutputNormal),

		// type definitions
		"Attribute":   reflect.ValueOf((*gocui.Attribute)(nil)),
		"Editor":      reflect.ValueOf((*gocui.Editor)(nil)),
		"EditorFunc":  reflect.ValueOf((*gocui.EditorFunc)(nil)),
		"Gui":         reflect.ValueOf((*gocui.Gui)(nil)),
		"Key":         reflect.ValueOf((*gocui.Key)(nil)),
		"Manager":     reflect.ValueOf((*gocui.Manager)(nil)),
		"ManagerFunc": reflect.ValueOf((*gocui.ManagerFunc)(nil)),
		"Modifier":    reflect.ValueOf((*gocui.Modifier)(nil)),
		"OutputMode":  reflect.ValueOf((*gocui.OutputMode)(nil)),
		"View":        reflect.ValueOf((*gocui.View)(nil)),

		// interface wrapper definitions
		"_Editor":  reflect.ValueOf((*_github_com_jroimartin_gocui_Editor)(nil)),
		"_Manager": reflect.ValueOf((*_github_com_jroimartin_gocui_Manager)(nil)),
	}
}

// _github_com_jroimartin_gocui_Editor is an interface wrapper for Editor type
type _github_com_jroimartin_gocui_Editor struct {
	IValue interface{}
	WEdit  func(v *gocui.View, key gocui.Key, ch rune, mod gocui.Modifier)
}

func (W _github_com_jroimartin_gocui_Editor) Edit(v *gocui.View, key gocui.Key, ch rune, mod gocui.Modifier) {
	W.WEdit(v, key, ch, mod)
}

// _github_com_jroimartin_gocui_Manager is an interface wrapper for Manager type
type _github_com_jroimartin_gocui_Manager struct {
	IValue  interface{}
	WLayout func(a0 *gocui.Gui) error
}

func (W _github_com_jroimartin_gocui_Manager) Layout(a0 *gocui.Gui) error {
	return W.WLayout(a0)
}
