// Code generated by 'yaegi extract github.com/zuiwuchang/gosdk'. DO NOT EDIT.

package symbols

import (
	"github.com/zuiwuchang/gosdk"
	"reflect"
)

func init() {
	Symbols["github.com/zuiwuchang/gosdk/gosdk"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AppCommit":  reflect.ValueOf(&gosdk.AppCommit).Elem(),
		"AppDate":    reflect.ValueOf(&gosdk.AppDate).Elem(),
		"AppVersion": reflect.ValueOf(&gosdk.AppVersion).Elem(),
		"Args":       reflect.ValueOf(&gosdk.Args).Elem(),
		"Dir":        reflect.ValueOf(&gosdk.Dir).Elem(),
		"Yaegi":      reflect.ValueOf(&gosdk.Yaegi).Elem(),
	}
}
